23 choices from question
collecthor/surveyjs-parser pull request #50
Opened 2022-10-19 12:31 UTC by radwouters

Closes #23

2022-10-19 14:48 UTC, SamMousa requested changes

2022-10-20 06:21 UTC, radwouters commented on src/Parsers/MultipleChoiceQuestionParser.php
> +                    $variable = $set->getVariable($questionConfig['choicesFromQuestion']);
Good point, did not think about the misconfiguration possiblitity

2022-10-20 06:44 UTC, radwouters commented on src/Variables/DeferredVariable.php
> +    public function __construct(private string $name, Closure $closure)
this does not work with the above suggestion of annotating the closure. I also did this on purpose, to first check if the closure actually meets all requirements and then assign it, which in my opinion is cleaner than only using errors.

2022-12-30 15:17 UTC, SamMousa approved these changes

2022-12-30 15:17 UTC, merged